package com.playmotech.api.core.dto;

import java.util.List;

import com.playmotech.api.core.constants.GameFormat;
import com.playmotech.api.core.constants.MatchStatus;

import jakarta.validation.constraints.NotNull;
import lombok.Data;

@Data
public class CreateBadmintonMatchDto {
    private String id;
    // private List<String> teamIds;
    private List<TeamDto> teamIds; //modelMapper wont work
    private List<TeamPlayerDto> players; //modelMapper wont work
    @NotNull(message = "Max Points Required.")
    private Integer maxPoints;
    @NotNull(message = "Max Rounds Required.")
    private Integer maxRounds;
    private String scorerUserId;
    private String refereeUserId;
    private String matchOfficialUserId;
    private Boolean isLivestreamed;
    private Boolean isRecordingEnabled;
    @NotNull(message = "Game format required.")
    private GameFormat gameFormat;
    @NotNull(message = "Match status required.")
    private MatchStatus matchStatus;
    private String courtId;
    private String scheduledStartTime;
    private String tournamentId;
    private Boolean isAutogenerated;

}
