package com.playmotech.api.core.dto;

import java.sql.Timestamp;
import java.util.List;

import com.playmotech.api.core.constants.GameFormat;
import com.playmotech.api.core.constants.MatchStatus;
import com.playmotech.api.core.constants.StreamingStatus;
import com.playmotech.api.core.services.impl.PickleBallTeamPlayerDto;

import lombok.Data;

@Data
// @Builder
public class PickleballMatchDto {
    private String id;
    private String startTime;
    private String endTime;
    private List<PickleballTeamDto> teams; // modelMapper wont work
    private List<PickleBallTeamPlayerDto> players; // modelMapper wont work
    private Integer maxPoints;
    private Integer maxRounds;
    private UserProfileMinDto scorer;
    private UserProfileMinDto referee;
    private UserProfileMinDto matchOfficial;
    private MatchStatus matchStatus;
    private Boolean isLivestreamed;
    private Boolean isRecordingEnabled;
    private GameFormat gameFormat;
    private CourtDto court;
    private String scheduledStartTime;
    private String tournamentId;
    private StreamingStatus streamingStatus;
    private String streamingChannel;
    private String streamingToken;
    private String createdByUserId;
    private UserProfileMinDto createdByUserProfile;
    private Boolean canManage;
    private Boolean isAutogenerated;
    private List<PickleballPlayerScoreDto> rounds;
    private Timestamp createdAtTimestampUtc;
}
