package com.playmotech.api.core.services;

import java.util.List;

import com.playmotech.api.core.constants.Sports;
import com.playmotech.api.core.dao_postgres.BadmintonTournament;
import com.playmotech.api.core.dto.BadmintonTournamentDto;
import com.playmotech.api.core.dto.FileObjectDto;
import com.playmotech.api.core.dto.MediaDto;
import com.playmotech.api.core.dto.PaginatedResponse;
import com.playmotech.api.core.dto.TournamentPerformanceDto;
import com.playmotech.api.core.dto.TournamentTeamMappingDto;
import com.playmotech.api.core.dto.UpdateBadmintonTournamentDto;
import com.playmotech.api.core.dto.UserProfileMinDto;
import com.playmotech.api.core.exceptions.ResourceException;
import com.playmotech.api.core.utils.GenericFilter;

public interface IBadmintonTournamentService
                extends
                ITournamentService<BadmintonTournamentDto, BadmintonTournamentDto, UpdateBadmintonTournamentDto> {
        BadmintonTournamentDto convertToDto(String userId, BadmintonTournament badmintonTournament, Sports sport)
                        throws ResourceException;

        TournamentPerformanceDto getTournamentPerformance(String tournamentId, Sports sport) throws ResourceException;

        List<MediaDto> uploadGalleryMedia(String tournamentId, List<FileObjectDto> fileObjectDtos, Sports sport)
                        throws ResourceException;

        void deleteGalleryMedia(String tournamentId, Long mediaId, Sports sport) throws ResourceException;

        void deleteAllAutogeneratedMatches(String academyId, String tournamentId, Sports sport)
                        throws ResourceException;

        List<UserProfileMinDto> addPlayersToTournament(String tournamentId, List<String> playerIds, Sports sport)
                        throws ResourceException;

        void deletePlayersFromTournament(String tournamentId, String playerUserId, Sports sport)
                        throws ResourceException;

        List<UserProfileMinDto> getTournanentPlayers(String searchTxt, String tournamentId, Sports sport)
                        throws ResourceException;

        void mapTeamsToTournament(String userId, String tournamentId,
                        TournamentTeamMappingDto tournamentTeamMappingDtos,
                        String academyId, Sports sport)
                        throws ResourceException;

        PaginatedResponse<BadmintonTournamentDto> getTournamentsPaginated(String userId, GenericFilter filter,
                        Sports sport) throws ResourceException;
}
