package com.playmotech.api.core.services;

import java.util.List;
import java.util.Map;

import org.apache.commons.lang3.tuple.Pair;

import com.playmotech.api.core.constants.Sports;
import com.playmotech.api.core.constants.StreamingStatus;
import com.playmotech.api.core.dao_postgres.BadmintonMatch;
import com.playmotech.api.core.dto.BadmintonMatchDetailDto;
import com.playmotech.api.core.dto.BadmintonMatchDetailRequestDto;
import com.playmotech.api.core.dto.BadmintonMatchDto;
import com.playmotech.api.core.dto.BadmintonScoreTrendDto;
import com.playmotech.api.core.dto.CreateBadmintonMatchDto;
import com.playmotech.api.core.dto.PaginatedResponse;
import com.playmotech.api.core.dto.PlayerPerformanceDto;
import com.playmotech.api.core.dto.RealTimeScoreUpdateRequestDto;
import com.playmotech.api.core.dto.UpdateBadmintonMatchDto;
import com.playmotech.api.core.exceptions.ResourceException;
import com.playmotech.api.core.utils.GenericFilter;

public interface IBadmintonMatchService
                extends IMatchService<CreateBadmintonMatchDto, BadmintonMatchDto, UpdateBadmintonMatchDto> {
        BadmintonMatchDto convertToDto(String userId, BadmintonMatch match, Sports sport) throws ResourceException;

        List<BadmintonMatchDto> convertToDto(String userId, List<BadmintonMatch> match, Sports sport)
                        throws ResourceException;

        Map<String, String> streamMatch(String matchId, StreamingStatus status, Sports sport) throws ResourceException;

        BadmintonMatchDetailDto submitMatchDetails(String matchId,
                        BadmintonMatchDetailRequestDto badmintonMatchDetailRequestDto, Sports sport)
                        throws ResourceException;

        BadmintonMatchDetailDto getMatchDetails(String matchId, Sports sport) throws ResourceException;

        // void submitScore(String matchId, BadmintonScoreRequestDto
        // badmintonScoreRequestDto, Sports sport) throws ResourceException;

        void deleteAllAutogeneratedMatchesByTournament(String academyId, String tournamentId, Sports sport)
                        throws ResourceException;

        Pair<Long, Long> getMatchCounts(String tournamentId, Sports sport) throws ResourceException;

        List<PlayerPerformanceDto> getGuestPlayerPerformances(String tournamentId, Sports sport)
                        throws ResourceException;

        List<PlayerPerformanceDto> getPlayerPerformances(String tournamentId, Sports sport) throws ResourceException;

        // TODO: pending work for pickleball sports
        void updateRealTimeScore(String matchId, RealTimeScoreUpdateRequestDto requestDto) throws ResourceException;

        // TODO: pending work for pickleball sports
        void finalizeMatchScores(String matchId, BadmintonMatchDetailRequestDto finalScores, Sports sport)
                        throws ResourceException;

        List<BadmintonScoreTrendDto> getScoreTrend(String matchId, Long roundNumber, Sports sport)
                        throws ResourceException;

        Map<String, Map<String, Long>> getScoreByShot(String matchId, Long roundNumber, Sports sport)
                        throws ResourceException;

        PaginatedResponse<BadmintonMatchDto> getMatchesByStatusSpecification(String userId, GenericFilter filter,
                        Sports sport) throws ResourceException;
}
