package com.playmotech.api.core.services;

import java.util.List;
import java.util.Map;

import org.apache.commons.lang3.tuple.Pair;

import com.playmotech.api.core.constants.Sports;
import com.playmotech.api.core.constants.StreamingStatus;
import com.playmotech.api.core.dao_postgres.PickleballMatch;
import com.playmotech.api.core.dto.BadmintonScoreTrendDto;
import com.playmotech.api.core.dto.CreatePickleballMatchDto;
import com.playmotech.api.core.dto.PaginatedResponse;
import com.playmotech.api.core.dto.PickleballMatchDetailDto;
import com.playmotech.api.core.dto.PickleballMatchDetailRequestDto;
import com.playmotech.api.core.dto.PickleballMatchDto;
import com.playmotech.api.core.dto.PlayerPerformanceDto;
import com.playmotech.api.core.dto.RealTimeScoreUpdateRequestDto;
import com.playmotech.api.core.dto.UpdatePickleballMatchDto;
import com.playmotech.api.core.exceptions.ResourceException;
import com.playmotech.api.core.utils.GenericFilter;

public interface IPickleballMatchService
                extends IMatchService<CreatePickleballMatchDto, PickleballMatchDto, UpdatePickleballMatchDto> {
        PickleballMatchDto convertToDto(String userId, PickleballMatch match, Sports sport) throws ResourceException;

        List<PickleballMatchDto> convertToDto(String userId, List<PickleballMatch> match, Sports sport)
                        throws ResourceException;

        Map<String, String> streamMatch(String matchId, StreamingStatus streamingStatus) throws ResourceException;

        PickleballMatchDetailDto submitMatchDetails(String matchId,
                        PickleballMatchDetailRequestDto pickleballMatchDetailRequestDto, Sports sport)
                        throws ResourceException;

        PickleballMatchDetailDto getMatchDetails(String matchId, Sports sport) throws ResourceException;

        // void submitScore(String matchId, PickleballScoreRequestDto
        // pickleballScoreRequestDto, Sports sport) throws ResourceException;

        void deleteAllAutogeneratedMatchesByTournament(String academyId, String tournamentId, Sports sport)
                        throws ResourceException;

        Pair<Long, Long> getMatchCounts(String tournamentId) throws ResourceException;

        List<PlayerPerformanceDto> getGuestPlayerPerformances(String tournamentId) throws ResourceException;

        List<PlayerPerformanceDto> getPlayerPerformances(String tournamentId) throws ResourceException;

        void updateRealTimeScore(String matchId, RealTimeScoreUpdateRequestDto requestDto) throws ResourceException;

        void finalizeMatchScores(String matchId, PickleballMatchDetailRequestDto finalScores) throws ResourceException;

        List<BadmintonScoreTrendDto> getScoreTrend(String matchId, Long roundNumber) throws ResourceException;

        Map<String, Map<String, Long>> getScoreByShot(String matchId, Long roundNumber) throws ResourceException;

        PaginatedResponse<PickleballMatchDto> getMatchesByStatusSpecification(String userId, GenericFilter filter)
                        throws ResourceException;

}
