package com.playmotech.api.core.services;

import java.util.List;

import com.playmotech.api.core.constants.Sports;
import com.playmotech.api.core.dao_postgres.PickleballTournament;
import com.playmotech.api.core.dto.FileObjectDto;
import com.playmotech.api.core.dto.MediaDto;
import com.playmotech.api.core.dto.PaginatedResponse;
import com.playmotech.api.core.dto.PickleballTournamentDto;
import com.playmotech.api.core.dto.TournamentPerformanceDto;
import com.playmotech.api.core.dto.TournamentTeamMappingDto;
import com.playmotech.api.core.dto.UpdatePickleballTournamentDto;
import com.playmotech.api.core.dto.UserProfileMinDto;
import com.playmotech.api.core.exceptions.ResourceException;
import com.playmotech.api.core.utils.GenericFilter;

public interface IPickleballTournamentService
                extends
                ITournamentService<PickleballTournamentDto, PickleballTournamentDto, UpdatePickleballTournamentDto> {

        PickleballTournamentDto convertToDto(String userId, PickleballTournament pickleballTournament, Sports sport)
                        throws ResourceException;

        TournamentPerformanceDto getTournamentPerformance(String tournamentId) throws ResourceException;

        List<MediaDto> uploadGalleryMedia(String tournamentId, List<FileObjectDto> fileObjectDtos)
                        throws ResourceException;

        void deleteGalleryMedia(String tournamentId, Long mediaId) throws ResourceException;

        void deleteAllAutogeneratedMatches(String academyId, String tournamentId, Sports sport)
                        throws ResourceException;

        List<UserProfileMinDto> addPlayersToTournament(String tournamentId, List<String> playerIds)
                        throws ResourceException;

        void deletePlayersFromTournament(String tournamentId, String playerUserId) throws ResourceException;

        List<UserProfileMinDto> getTournamentPlayers(String searchTxt, String tournamentId) throws ResourceException;

        void mapTeamsToTournament(String userId, String tournamentId,
                        TournamentTeamMappingDto tournamentTeamMappingDtos,
                        String academyId) throws ResourceException;

        PaginatedResponse<PickleballTournamentDto> getTournamentsPaginated(String userId, GenericFilter filter)
                        throws ResourceException;
}
