package com.playmotech.api.core.repo;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.playmotech.api.core.constants.MatchStatus;
import com.playmotech.api.core.dao_postgres.BadmintonMatch;

import jakarta.persistence.Tuple;
import jakarta.transaction.Transactional;

@Repository
public interface BadmintonMatchRepo
		extends CrudRepository<BadmintonMatch, String>, JpaSpecificationExecutor<BadmintonMatch> {
	List<BadmintonMatch> findByMatchStatusAndAcademy_Id(MatchStatus matchStatus, String acedemyId);

	List<BadmintonMatch> findByMatchStatusIn(List<MatchStatus> matchStatuses);

	List<BadmintonMatch> findByMatchStatusInAndTournament_Id(List<MatchStatus> matchStatuses, String tournamentId);

	List<BadmintonMatch> findByMatchStatusAndAcademy_IdAndTournament_Id(MatchStatus matchStatus, String acedemyId,
			String tournamentId);

	List<BadmintonMatch> findByMatchStatusAndTournament_Id(MatchStatus matchStatus, String tournamentId);

	List<BadmintonMatch> findByAcademy_Id(String acedemyId);

	List<BadmintonMatch> findByAcademy_IdAndTournament_Id(String acedemyId, String tournamentId);

	List<BadmintonMatch> findByTournament_Id(String tournamentId);

	Optional<BadmintonMatch> findByAcademy_IdAndId(String acedemyId, String id);

	Optional<BadmintonMatch> findByAcademyIsNullAndId(String id);

	List<BadmintonMatch> findByAcademyIsNullAndTournament_Id(String tournamentId);

	@Modifying
	@Transactional
	@Query("UPDATE BadmintonMatch m SET m.streamingStatus = 'STARTED', m.streamingChannel = :streamingChannel, m.streamingToken = :streamingToken WHERE m.id = :id")
	void startStreaming(@Param("id") String id, @Param("streamingChannel") String streamingChannel,
			@Param("streamingToken") String streamingToken);

	@Modifying
	@Transactional
	@Query("UPDATE BadmintonMatch m SET m.streamingStatus = 'ENDED' WHERE m.id = :id")
	void endStreaming(@Param("id") String id);

	@Modifying
	@Transactional
	@Query("DELETE FROM BadmintonMatch m WHERE m.tournament.id = :tournamentId AND m.isAutogenerated = true")
	void deleteByAutogenMatchesByTournament(@Param("tournamentId") String tournamentId);

	@Query(value = """
			      SELECT
			      COUNT(DISTINCT CASE WHEN bm.match_status NOT IN ('NEW' , 'SCHEDULED') THEN bm.id END) AS total_matches_played,
			      COUNT(DISTINCT CASE WHEN bm.match_status = 'ENDED'  THEN bm.id END) AS total_matches_completed
			      FROM badminton_matches bm
			      WHERE bm.badminton_tournament_id = :tournamentId
			""", nativeQuery = true)
	List<Tuple> getMatchesCount(@Param("tournamentId") String tournamentId);
}
