package com.playmotech.api.core.repo;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.playmotech.api.core.constants.MatchStatus;
import com.playmotech.api.core.dao_postgres.PickleballMatch;

import jakarta.persistence.Tuple;
import jakarta.transaction.Transactional;

@Repository
public interface PickleballMatchRepo
        extends JpaRepository<PickleballMatch, String>, JpaSpecificationExecutor<PickleballMatch> {
    Optional<PickleballMatch> findByAcademy_IdAndId(String academyId, String id);

    Optional<PickleballMatch> findByAcademyIsNullAndId(String id);

    List<PickleballMatch> findByMatchStatusIn(List<MatchStatus> matchStatus);

    List<PickleballMatch> findByMatchStatusAndAcademy_Id(MatchStatus matchStatus, String academyId);

    List<PickleballMatch> findByMatchStatusAndTournament_Id(MatchStatus matchStatus, String tournamentId);

    List<PickleballMatch> findByMatchStatusAndAcademy_IdAndTournament_Id(MatchStatus matchStatus, String academyId,
            String tournamentId);

    List<PickleballMatch> findByAcademy_Id(String academyId);

    List<PickleballMatch> findByTournament_Id(String tournamentId);

    List<PickleballMatch> findByAcademy_IdAndTournament_Id(String academyId, String tournamentId);

    @Modifying
    @Transactional
    @Query("UPDATE PickleballMatch m SET m.streamingStatus = 'STARTED', m.streamingChannel = :streamingChannel, m.streamingToken = :streamingToken WHERE m.id = :id")
    void startStreaming(@Param("id") String id, @Param("streamingChannel") String streamingChannel,
            @Param("streamingToken") String streamingToken);

    @Modifying
    @Transactional
    @Query("UPDATE PickleballMatch m SET m.streamingStatus = 'ENDED' WHERE m.id = :id")
    void endStreaming(@Param("id") String id);

    @Query(value = """
                  SELECT
                  COUNT(DISTINCT CASE WHEN bm.match_status NOT IN ('NEW' , 'SCHEDULED') THEN bm.id END) AS total_matches_played,
                  COUNT(DISTINCT CASE WHEN bm.match_status = 'ENDED'  THEN bm.id END) AS total_matches_completed
                  FROM pickleball_matches bm
                  WHERE bm.pickleball_tournament_id = :tournamentId
            """, nativeQuery = true)
    List<Tuple> getMatchesCount(@Param("tournamentId") String tournamentId);

    List<PickleballMatch> findByMatchStatusInAndTournament_Id(List<MatchStatus> matchStatuses, String tournamentId);

    @Modifying
    @Transactional
    @Query("DELETE FROM PickleballMatch m WHERE m.tournament.id = :tournamentId AND m.isAutogenerated = true")
    void deleteByAutogenMatchesByTournament(String tournamentId);
}
