package com.playmotech.api.core.mapper;

import org.springframework.beans.BeanUtils;

import com.playmotech.api.core.dao_postgres.UserProfile;
import com.playmotech.api.core.dao_postgres.VideoAnalysis;
import com.playmotech.api.core.dao_postgres.VideoAnalyzer;
import com.playmotech.api.core.dto.VideoAnalysisDto;
import com.playmotech.api.core.response.dao.UserProfileDao;
import com.playmotech.api.core.response.dao.VideoAnalysisDao;

public class VideoAnalysisMapper {

	public static VideoAnalysisDao mapEntityToDao(VideoAnalysis entity) {
		VideoAnalysisDao dao = new VideoAnalysisDao();

		// Copy simple properties
		BeanUtils.copyProperties(entity, dao);

		if (entity.getAnalysedByUser() != null) {
			UserProfileDao userProfileDao = new UserProfileDao();
			userProfileDao.setId(entity.getAnalysedByUser().getId());
			dao.setAnalysedByUser(userProfileDao);
		}

		return dao;
	}

	public static VideoAnalysis mapDtoToEntity(VideoAnalysisDto dto, VideoAnalyzer analyzer) {
		VideoAnalysis entity = new VideoAnalysis();

		// Copy simple properties (ignore 'id' as it is auto-generated by JPA)
		BeanUtils.copyProperties(dto, entity, "id");

		// Handle relationships

		// AnalysedByUser relationship mapping
		if (analyzer.getCreatedBy() != null) {
//			UserProfile userProfile = new UserProfile();
//			userProfile.setId(dto.getAnalysedByUser()); // Set the user ID
			entity.setAnalysedByUser(analyzer.getCreatedBy()); // Set the relationship
		}

		// Set other fields
		if (dto.getVideoFrameTime() != null) {
			entity.setVideoFrameTime(dto.getVideoFrameTime());
		}
		if (dto.getAudioMediaUrl() != null) {
			entity.setAudioMediaUrl(dto.getAudioMediaUrl());
		}
		if (dto.getImageUrl() != null) {
			entity.setImageUrl(dto.getImageUrl());
		}
		if (dto.getComment() != null) {
			entity.setComment(dto.getComment());
		}

		// Set the parent VideoAnalyzer (which is passed as a parameter)
		entity.setVideoAnalyzer(analyzer);

		return entity;
	}

	public static VideoAnalysis mapDtoToExistingEntity(VideoAnalysisDto dto, VideoAnalysis entity,
			UserProfile analysedUser) {

		BeanUtils.copyProperties(dto, entity);

		// Update simple properties
		if (analysedUser != null) {
//			UserProfile userProfile = new UserProfile();
//			userProfile.setId(dto.getAnalysedByUser());
			entity.setAnalysedByUser(analysedUser);
		}
		if (dto.getVideoFrameTime() != null) {
			entity.setVideoFrameTime(dto.getVideoFrameTime());
		}
		if (dto.getAudioMediaUrl() != null) {
			entity.setAudioMediaUrl(dto.getAudioMediaUrl());
		}
		if (dto.getImageUrl() != null) {
			entity.setImageUrl(dto.getImageUrl());
		}
		if (dto.getComment() != null) {
			entity.setComment(dto.getComment());
		}

		return entity;
	}

}
