package com.playmotech.api.core.dao_postgres;

import java.sql.Timestamp;
import java.util.List;

import com.playmotech.api.core.constants.GameFormat;
import com.playmotech.api.core.constants.MatchStatus;
import com.playmotech.api.core.constants.StreamingStatus;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Table(name = "pickleball_matches")
@Entity
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PickleballMatch {
    @Id
    private String id;

    @ManyToOne
    @JoinColumn(name = "academy_id", referencedColumnName = "id")
    private Academy academy;

    @ManyToOne
    @JoinColumn(name = "court_id", referencedColumnName = "id")
    private Court court;

    @Column(name = "start_time")
    private String startTime;

    @Column(name = "end_time")
    private String endTime;

    @ManyToMany(mappedBy = "pickleballMatch", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private List<PickleballTeamMapping> teams;

    @ManyToMany(mappedBy = "pickleballMatch", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private List<PickleballSinglesPlayerMapping> singlePlayers;

    @Column(name = "max_points")
    private Integer maxPoints;

    @Column(name = "max_rounds")
    private Integer maxRounds;

    @ManyToOne
    @JoinColumn(name = "scorer_user_id", referencedColumnName = "id")
    private UserProfile scorerUserProfile;

    @ManyToOne
    @JoinColumn(name = "referee_user_id", referencedColumnName = "id")
    private UserProfile refereeUserProfile;

    @ManyToOne
    @JoinColumn(name = "match_official_user_id", referencedColumnName = "id")
    private UserProfile matchOfficialUserProfile;

    @Column(name = "created_at_timestamp_utc")
    private Timestamp createdAtTimestampUtc;

    @Column(name = "updated_at_timestamp_utc")
    private Timestamp updatedAtTimestampUtc;

    @Column(name = "match_status")
    @Enumerated(EnumType.STRING)
    private MatchStatus matchStatus;

    @Column(name = "is_livestreamed")
    private Boolean isLivestreamed;

    @Column(name = "is_recording_enabled")
    private Boolean isRecordingEnabled;

    @Column(name = "game_format")
    @Enumerated(EnumType.STRING)
    private GameFormat gameFormat;

    @Column(name = "inactive")
    private Boolean inactive;

    @Column(name = "scheduled_start_time")
    private String scheduledStartTime;

    @ManyToOne
    @JoinColumn(name = "pickleball_tournament_id", referencedColumnName = "id")
    private PickleballTournament tournament;

    @Column(name = "streaming_status")
    @Enumerated(EnumType.STRING)
    private StreamingStatus streamingStatus;

    @Column(name = "streaming_channel")
    private String streamingChannel;

    @Column(name = "streaming_token")
    private String streamingToken;

    @ManyToOne
    @JoinColumn(name = "created_by_user_id", referencedColumnName = "id")
    private UserProfile createdByUserProfile;

    @Column(name = "is_autogenerated")
    private Boolean isAutogenerated;

    @ManyToMany(mappedBy = "pickleballMatch", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private List<PickleballMatchTeamPlayerMapping> pickleballMatchTeamPlayers;
}
